EXP_DIR: "pascal_config"
LESSEN_DEBUG_TIME: True
TRAIN:
  USE_FLIPPED: True
  SNAPSHOT_ITERS: 80
  MAX_SIZE: 1000
  IMS_PER_BATCH: 2
  BATCH_SIZE: 4
  FG_NUMBER: 1
  FG_THRESH_LO: 0.5
  FG_THRESH_HI: 0.95
  FG_ITSELF_THRESH: 1.0
  BG_THRESH_LO: 0.1
  BG_THRESH_HI: 0.45
  HAS_SECONDARY_REGIONS: True
  NEED_WHOLE_IMAGE_BBOX: True
  HAS_VISUAL_BBOX: False
  VISUAL_BBOX_LEN: 5
TEST:
  TEST_INTERVAL: 4000
  START_TEST_ITER: 10000
  IMS_PER_BATCH: 1
  SCALES: !!python/tuple [600,]
  MAX_SIZE: 1000
  SR_PER_NUMBER: 100
  SR_ITSELF_THRESH: 1.0
  SR_FG_THRESH_LO: 0.2
  SR_FG_THRESH_HI: 0.75
  SR_FG_COPY_PER_NUMBER: 1
  HAS_SECONDARY_REGIONS: True
  NEED_WHOLE_IMAGE_BBOX: True
  HAS_FG_SECONDARY_REGIONS: False
  HAS_CONTROL_THE_SAME_SCALE: False
  HAS_SHOW_REGION: True
  HAS_SHOW_SECONDARY_REGION: True
  HAS_VISUAL_BBOX: False
  VISUAL_BBOX_LEN: 5

