EXP_DIR: "pascal_config"
TRAIN:
  MAX_SIZE: 1000
  IMS_PER_BATCH: 2
  BATCH_SIZE: 30
  FG_NUMBER: 14
  FG_THRESH_LO: 0.5
  FG_THRESH_HI: 0.95
  FG_ITSELF_THRESH: 1.0
  BG_THRESH_LO: 0.1
  BG_THRESH_HI: 0.45
  SNAPSHOT_ITERS: 4000
  BBOX_REG: False
  USE_FLIPPED: True
  HAS_VISUAL_BBOX: False
  NEED_WHOLE_IMAGE_BBOX: True
TEST:
  BBOX_REG: False

